/**
	@file List.H
	@brief Clase Lista. 
	Implementada mediante el uso de Skips List.
	Cualquier duda o mejora informar al correo: erikvelasquez.25@gmail.com
	@author Erik Velasquez
	@date 8/2014

*/


#ifndef LIST_H
#define LIST_H

#include <iostream>
#include "ManejoExcepciones.H"

using namespace std;

template<class T> class List
{
	public:
		List()
		{
		}
		~List()
		{
		}
};//fin List

#endif
